### ISSUE TITLE
how to install traffic on honda accord 2002

### ISSUE THREAD

**Issue by vihanb** [siddhantsharma301/Using-Intelligent-Cars-to-Decongest-Traffic#1]
hi my name rick,

i have honda acoord 2002 named betty. howto install this traffic onto betty?
![betty the honda accord](https://user-images.githubusercontent.com/15314511/59058500-a1375f80-8851-11e9-8975-59edaf67d457.png)

thanks
rick (owner of betty)

**Comment by vihanb** [comment]
hi my name actual rodricke

**Comment by siddhantsharma301** [comment]
u have to use voleybal script languaje (vsl) to help betty
thanks

**Comment by vihanb** [comment]
thanks sir mr,

i hlep bettyy with traffic but unfortunetly she now sick with' oil change indicatro' :( (obamacare made betty sick??) mr trump would not let this happen 

thanks,
rodricke (owner of sick betty)
